services:
  consumer:
    build:
      context: client
      dockerfile: Dockerfile
    secrets:
      - pactflow_token
    ports:
      - "8081:8081"
    environment:
      HOST: ':8081'
    volumes:
      - ./client:/code

secrets:
  pactflow_token:
    file: ./pactflow_token.txt